// Static config for the LEF calendar scraper.
// All vendor-specific knobs live here so src/scrape.js stays small.

export const GRAPHQL_URL = 'https://portal.lefclimbing.com/graphql-public';

// `Language` enum value accepted by rphq's API. Confirmed via error response.
export const LANGUAGE = 'ENGLISH';

// CalendarFilter shape (minus startDate/endDate/planId, which are filled in
// dynamically per-request).
//
// - facilityId: LEF's facility node (Relay global ID). Decodes to "Facility:10000009".
//   The Redpoint HQ storefront at portal.lefclimbing.com is shared with Mosaic
//   (Facility:10000012), so this id is what scopes the calendar to LEF.
//   To re-capture if LEF ever re-keys: load any LEF program page, e.g.
//   https://portal.lefclimbing.com/lef/programs/green-team , and read
//   `sessionFilter.facilityId` from the GraphQL request the SPA fires.
// - planId: NOT here. Comes from src/portal-visible-plan-ids.js, generated by
//   scripts/discover-plan-ids.mjs (LEF has no public calendar SPA to mirror).
export const CALENDAR_INPUT_EXTRA = {
  facilityId: ['RmFjaWxpdHk6MTAwMDAwMDk='],
};

// Page size for the StorefrontPlansQuery. LEF's shared catalog is ~139 plans,
// so 250 covers it with headroom.
export const PLANS_PAGE_SIZE = 250;

// The portal rejects multi-month ranges ("short time frame"); 21-day windows
// mirror what the vendor SPA itself requests.
export const WINDOW_DAYS = 21;

// How far ahead to scrape. 6 months covers Summer Camp + Boulder League + a
// full recurring-class horizon without hammering the API.
export const MONTHS_AHEAD = 6;

// The `calendar` query requires BOTH facilityId AND a planId allowlist (an
// unfiltered query 500s). LEF's portal has no public calendar page to mirror,
// so scripts/discover-plan-ids.mjs builds the allowlist as: every LEF-facility
// plan that has scheduled sessions in the horizon, MINUS the slugs below.
// These are high-volume *bookable slots* (day passes, group-event day passes,
// 1:1 private lessons) — reservation inventory, not public events.
export const EVENT_PLAN_DENYLIST =
  /(day-pass|group-rates|group-events|private-lesson|guest-pass)/i;

// Heuristic mapping from a publicTitle to one of our four UI categories.
// Order matters — first match wins. `member` is checked BEFORE `youth` so a
// "Member Events | Blue/Black" grade-night isn't miscategorized as youth on the
// word "Blue". Tuned to LEF's program names:
//   member  → Member Events (any "Member Events | …" grade night / meet-up)
//   youth   → Green/Blue/Purple Club, Advanced Team, Summer Camp
//   workshop → Top Rope Class, Lead Class, Gym to Crag, Yoga, Boulder League,
//              Climbing 101, Hangboarding
//   event   → anything else
export const CATEGORY_RULES = [
  { test: /\b(member|meet[\s-]?up)\b/i, category: 'member' },
  { test: /\b(camps?|kids|youth|teen|club|green|blue|purple|team)\b/i, category: 'youth' },
  { test: /\b(learn|intro|belay|technique|workshop|clinic|lesson|class|league|training|yoga|hangboard|lead|crag|101|sign[\s-]?up)\b/i, category: 'workshop' },
];
